fix before-start and on-start

diff --git a/ams b/ams
--- a/ams
+++ b/ams
@@ -525,15 +525,17 @@ fi
 
 # run before-start script
 if [ "$full" = "true" ] || [ "$build" = "true"  ]; then
-    get_json_file_value "$DEF_FILE" "before-start"
-    BEFORE_START_SCRIPT="$BASEDIR/containers/$NODE/$JSON_VALUE"
-    if [ -f "$BEFORE_START_SCRIPT" ]; then
-        info "Running before-start init script"
-        if sh "$BEFORE_START_SCRIPT"; then 
-            info "before-start initialization successful"
-        else 
-            error "Failed to finish before-start initialization"
-            exit 12
+    if [ ! "$user" = "true" ]; then
+        get_json_file_value "$DEF_FILE" "before-start"
+        BEFORE_START_SCRIPT="$BASEDIR/containers/$NODE/$JSON_VALUE"
+        if [ -f "$BEFORE_START_SCRIPT" ]; then
+            info "Running before-start init script"
+            if sh "$BEFORE_START_SCRIPT"; then 
+                info "before-start initialization successful"
+            else 
+                error "Failed to finish before-start initialization"
+                exit 12
+            fi
         fi
     fi
 fi 
@@ -571,11 +573,13 @@ fi
 
 # run on-start script
 if [ "$full" = "true" ] || [ "$start" = "true" ]; then
-    get_json_file_value "$DEF_FILE" "on-start"
-    ON_START_SCRIPT="$BASEDIR/containers/$NODE/$JSON_VALUE"
-    if [ -f "$ON_START_SCRIPT" ]; then
-        info "Running on-start init script"
-        sh "$ON_START_SCRIPT"
+    if [ ! "$user" = "true" ]; then
+        get_json_file_value "$DEF_FILE" "on-start"
+        ON_START_SCRIPT="$BASEDIR/containers/$NODE/$JSON_VALUE"
+        if [ -f "$ON_START_SCRIPT" ]; then
+            info "Running on-start init script"
+            sh "$ON_START_SCRIPT"
+        fi
     fi
 fi 
 
